"""add_images_list

Revision ID: 98fba050e891
Revises: e084029928bd
Create Date: 2025-12-26 20:33:57.914959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fba050e891'
down_revision: Union[str, Sequence[str], None] = 'e084029928bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stays', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('stays', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stays', 'images')
    op.drop_column('stays', 'image_url')
    # ### end Alembic commands ###
